### ISSUE TITLE
Support declarative format for deployment configurations

### ISSUE THREAD

**Issue by siddharthvp** [Eccenux/Wikiploy#2]
Wikiploy is a cool tool, but the need to write JavaScript code for deploy configurations seems avoidable. The package can be easier to use if it allows configurations in a declarative format like YAML. The JS API can of course be retained for advanced scenarios with custom edit summaries, etc.

Example `wikiploy.yml` file to be placed in repo root:

```
dev:
  site: test.wikipedia.org
  source: src/xyz.js
  destination: User:SD0001/xyz.js

prod:
  site: en.wikipedia.org
  source: src/xyz.js
  destination: User:SD0001/sandbox/xyz.js
```

The format can be easily expanded to support multiple files per configuration, edit summaries with placeholder substitutions, etc.

Running `npx wikiploy dev` would deploy using the `dev` configuration, and so on.
